const variables = {
  OK: "OK",
  NOT_FOUND: "NOT_FOUND",
  DUPLICATE_ENTITY: "DUPLICATE_ENTITY",
  ALREADY_USED_ELSEWHERE: "ALREADY_USED_ELSEWHERE",
  ARGUMENT_NOT_VALID: "ARGUMENT_NOT_VALID",
  EXCEPTION: "EXCEPTION"
};

export default variables;
