const variables = {
  OK: "OK",
  NOT_FOUND: "NOT_FOUND",
  DUPLICATE_ENTITY: "DUPLICATE_ENTITY",
  ALREADY_USED_ELSEWHERE: "ALREADY_USED_ELSEWHERE",
  ARGUMENT_NOT_VALID: "ARGUMENT_NOT_VALID",
  NOT_MATCH: "NOT_MATCH",
  DUPLICATE_LEVEL: "DUPLICATE_LEVEL",
  NOT_SUITABLE: "NOT_SUITABLE",
  EXCEPTION: "EXCEPTION"
};

export const COSTUME_TYPE = {
  COMMON: "THÔNG THƯỜNG",
  SPECIFIC: "ĐẶC TRƯNG"
};

export default variables;
